/** HTTP transport and serving for graphs generated by the web launcher. */

import type { IncomingMessage, ServerResponse } from "node:http";
import { CliError } from "../errors";
import { sendHtml, sendJson, sendJsonFile } from "./http-response";
import { telemetrySourceDescriptors } from "./overlay-source";
import { SyntheticExecutionError } from "./synthetic-error";
import { githubTokenFor } from "./web-auth";
import { injectViewBoot, syntheticExecutionBootCapability } from "./web-boot";
import { WebError } from "./web-error";
import {
  isOperationCancelled,
  requestCancellation,
  responseCanWrite,
} from "./web-cancellation";
import { generateGraph } from "./web-generation";
import { parseGenerateRequest, readJsonBody } from "./web-request";
import type { Context } from "./web-server";

export async function handleGenerate(ctx: Context, request: IncomingMessage, response: ServerResponse): Promise<void> {
  if (acceptsNdjson(request)) {
    await handleGenerateStream(ctx, request, response);
    return;
  }
  const cancellation = requestCancellation(request, response);
  try {
    const parsed = parseGenerateRequest(await readJsonBody(request));
    const result = await generateGraph(
      ctx,
      parsed,
      githubTokenFor(ctx, request, parsed.token),
      undefined,
      cancellation.signal,
    );
    if (responseCanWrite(response)) sendJson(response, 200, result);
  } finally {
    cancellation.dispose();
  }
}

async function handleGenerateStream(ctx: Context, request: IncomingMessage, response: ServerResponse): Promise<void> {
  const cancellation = requestCancellation(request, response);
  beginNdjson(response);
  try {
    const parsed = parseGenerateRequest(await readJsonBody(request));
    const result = await generateGraph(ctx, parsed, githubTokenFor(ctx, request, parsed.token), (stage) =>
      writeLine(response, { stage }),
      cancellation.signal,
    );
    await writeLine(response, { stage: "done", ...result });
  } catch (error) {
    if (!isOperationCancelled(error) && responseCanWrite(response)) {
      await writeLine(response, { stage: "error", message: safeGenerateMessage(error) });
    }
  } finally {
    cancellation.dispose();
    if (responseCanWrite(response)) response.end();
  }
}

function acceptsNdjson(request: IncomingMessage): boolean {
  const accept = request.headers.accept;
  const value = Array.isArray(accept) ? accept.join(",") : (accept ?? "");
  return value
    .split(",")
    .some((part: string) => part.trim().split(";", 1)[0]?.toLowerCase() === "application/x-ndjson");
}

function beginNdjson(response: ServerResponse): void {
  response.writeHead(200, { "content-type": "application/x-ndjson; charset=utf-8", "cache-control": "no-cache" });
}

/** Resolve once Node has handed the line off, yielding before CPU-heavy extraction begins. */
function writeLine(response: ServerResponse, line: Record<string, unknown>): Promise<void> {
  if (!responseCanWrite(response)) return Promise.resolve();
  return new Promise((resolve, reject) => {
    response.write(`${JSON.stringify(line)}\n`, (error) => {
      if (error) {
        reject(error);
        return;
      }
      resolve();
    });
  });
}

function safeGenerateMessage(error: unknown): string {
  if (error instanceof SyntheticExecutionError || error instanceof WebError || error instanceof CliError) {
    return error.message;
  }
  return "internal error while generating the blueprint";
}

export async function sendGraph(ctx: Context, response: ServerResponse, id: string | null): Promise<void> {
  const path = id ? ctx.graphStore.artifactPath(id) : undefined;
  if (path === undefined) {
    sendJson(response, 404, { error: "unknown graph id" });
    return;
  }
  await sendJsonFile(response, path);
}

export function sendMeta(ctx: Context, response: ServerResponse, id: string | null): void {
  const descriptor = lookup(ctx, id);
  if (descriptor === undefined) {
    sendJson(response, 404, { error: "unknown graph id" });
    return;
  }
  const graphId = id as string;
  sendJson(response, 200, {
    schemaVersion: descriptor.summary.schemaVersion,
    generatedAt: descriptor.summary.generatedAt,
    nodeCount: descriptor.summary.nodeCount,
    hasOverlay: false,
    environments: [],
    telemetrySources: telemetrySourceDescriptors({ kind: "none" }),
    ...syntheticExecutionBootCapability(
      graphId,
      descriptor.source,
      descriptor.synthetic.scenarios,
      descriptor.synthetic.trust,
    ),
  });
}

export function sendView(ctx: Context, response: ServerResponse, id: string | null): void {
  const descriptor = lookup(ctx, id);
  if (descriptor === undefined) {
    sendHtml(response, "<!doctype html><meta charset=utf-8><title>Meridian</title><p>Unknown graph id.</p>", 404);
    return;
  }
  const graphId = id as string;
  sendHtml(response, injectViewBoot(
    ctx.rendererIndex,
    graphId,
    descriptor.source,
    descriptor.synthetic.scenarios,
    descriptor.synthetic.trust,
  ));
}

function lookup(ctx: Context, id: string | null) {
  return id ? ctx.graphStore.descriptor(id) : undefined;
}
