/** HTTP transport and serving for graphs generated by the web launcher. */

import { createHash } from "node:crypto";
import type { IncomingMessage, ServerResponse } from "node:http";
import { performance } from "node:perf_hooks";
import { CliError } from "../errors";
import { sendHtml, sendJson } from "./http-response";
import { telemetrySourceDescriptors } from "./overlay-source";
import {
  SyntheticExecutionError,
  syntheticExecutionRuntimeSupported,
} from "./synthetic-execution";
import { githubTokenFor } from "./web-auth";
import { injectViewBoot, syntheticExecutionBootCapability } from "./web-boot";
import { WebError } from "./web-error";
import { cancelWhenClientLeaves } from "./web-cancellation";
import { generateGraph } from "./web-generation";
import type { GenerateResult, GenerateStage } from "./web-generation";
import { webAnalysisKey } from "./web-cache";
import { parseGenerateRequest, readJsonBody } from "./web-request";
import type { GenerateRequest } from "./web-request";
import type { Context } from "./web-server";
import { InspectionQueueFullError } from "./inspection-scheduler";
import {
  BoundedGraphProjectionPageCache,
  defaultGraphProjectionRequest,
  GraphProjectionBundle,
  GraphSymbolSearchRequestError,
  readGraphProjectionManifest,
  type GraphProjectionCacheStats,
  type GraphProjectionQueryOptions,
  type GraphSymbolSearchRequest,
} from "./graph-projection-bundle";
import { handleGraphProjectionRequest } from "./graph-projection-response";
import type { ArtifactSource } from "./web-source";
import type { SyntheticExecutionTrust } from "./web-boot";
import type { GraphCapabilityHandle } from "./graph-capability-store";
import { reviewMetadataForContext } from "./review-comparison-context";

export async function handleGenerate(ctx: Context, request: IncomingMessage, response: ServerResponse): Promise<void> {
  const stream = acceptsNdjson(request);
  const cancellation = cancelWhenClientLeaves(request, response);
  const operationSignal = AbortSignal.any([cancellation.signal, ctx.shutdownSignal]);
  try {
    const parsed = parseGenerateRequest(await readJsonBody({ request, signal: operationSignal }));
    const token = githubTokenFor(ctx, request, parsed.token);
    let pending: Promise<GenerateResult>;
    try {
      pending = scheduleGeneration(ctx, parsed, token, operationSignal, stream
        ? (stage) => {
            // Scheduler progress callbacks are intentionally synchronous. Observe the transport
            // promise explicitly so a disconnect cannot become an unhandled rejection, and cancel
            // only this request's subscription when its response is no longer writable.
            void writeLine(response, { stage }).catch((error: unknown) => cancellation.abort(error));
          }
        : undefined);
    } catch (error) {
      throwQueueFull(response, error);
    }
    // Admission above is deliberately synchronous, so overload remains a real JSON 429 instead
    // of an error line hidden inside an already-committed HTTP 200 stream.
    if (!stream) {
      sendJson(response, 200, await pending);
      return;
    }
    beginNdjson(response);
    try {
      await writeLine(response, { stage: "done", ...await pending });
    } catch (error) {
      if (!operationSignal.aborted) {
        await writeLine(response, { stage: "error", message: safeGenerateMessage(error) });
      }
    } finally {
      response.end();
    }
  } finally {
    cancellation.dispose();
  }
}

function scheduleGeneration(
  ctx: Context,
  request: GenerateRequest,
  token: string | undefined,
  signal: AbortSignal,
  onProgress: ((stage: GenerateStage) => void) | undefined,
): Promise<GenerateResult> {
  if (!ctx.generationScheduler) {
    return generateGraph(ctx, request, token, onProgress, signal);
  }
  return ctx.generationScheduler.schedule(
    generationJobKey(request, token, ctx.refreshCache),
    {
      run: (executorSignal, reportProgress) => generateGraph(
        ctx,
        request,
        token,
        (stage) => reportProgress(stage),
        executorSignal,
        true,
      ),
    },
    { signal, onProgress: onProgress as ((stage: string) => void) | undefined },
  ) as Promise<GenerateResult>;
}

function generationJobKey(request: GenerateRequest, token: string | undefined, refreshCache: boolean): string {
  const { token: _requestToken, refresh: _requestRefresh, ...identity } = request;
  const credential = token ? createHash("sha256").update(token).digest("hex") : "anonymous";
  return createHash("sha256").update(JSON.stringify({
    identity,
    analysisKey: webAnalysisKey(request),
    credential,
    tokenExplicit: request.token !== undefined,
    // `--refresh-cache` and an explicit body refresh have identical execution semantics. Normalize
    // them so they share one executor and retain subscriber-aware cancellation.
    refresh: refreshCache || request.refresh === true,
  })).digest("hex");
}

function throwQueueFull(response: ServerResponse, error: unknown): never {
  if (error instanceof InspectionQueueFullError) {
    response.setHeader?.("retry-after", "5");
    throw new WebError(error.status, error.message);
  }
  throw error;
}

function acceptsNdjson(request: IncomingMessage): boolean {
  const accept = request.headers.accept;
  const value = Array.isArray(accept) ? accept.join(",") : (accept ?? "");
  return value
    .split(",")
    .some((part: string) => part.trim().split(";", 1)[0]?.toLowerCase() === "application/x-ndjson");
}

function beginNdjson(response: ServerResponse): void {
  response.writeHead(200, { "content-type": "application/x-ndjson; charset=utf-8", "cache-control": "no-cache" });
}

/** Resolve once Node has handed the line off, yielding before CPU-heavy extraction begins. */
function writeLine(response: ServerResponse, line: Record<string, unknown>): Promise<void> {
  return new Promise((resolve, reject) => {
    response.write(`${JSON.stringify(line)}\n`, (error) => {
      if (error) {
        reject(error);
        return;
      }
      resolve();
    });
  });
}

function safeGenerateMessage(error: unknown): string {
  if (error instanceof SyntheticExecutionError || error instanceof WebError || error instanceof CliError) {
    return error.message;
  }
  return "internal error while generating the blueprint";
}

function graphRequestLifecycle(
  ctx: Context,
  request: IncomingMessage,
  response: ServerResponse,
  message: string,
): { signal: AbortSignal; dispose(): void } {
  const client = cancelWhenClientLeaves(request, response, message);
  const signal = AbortSignal.any([client.signal, ctx.shutdownSignal]);
  const destroyRequest = () => {
    if (!request.destroyed) request.destroy();
  };
  signal.addEventListener("abort", destroyRequest, { once: true });
  if (signal.aborted) destroyRequest();
  return {
    signal,
    dispose() {
      signal.removeEventListener("abort", destroyRequest);
      client.dispose();
    },
  };
}

interface OwnedResource {
  release(): Promise<void>;
}

async function withOwnedResource<Resource extends OwnedResource, Result>(
  resource: Resource,
  label: string,
  use: (resource: Resource) => Promise<Result>,
): Promise<Result> {
  let failed = false;
  let failure: unknown;
  try {
    return await use(resource);
  } catch (error) {
    failed = true;
    failure = error;
    throw error;
  } finally {
    try {
      await resource.release();
    } catch (releaseError) {
      if (failed) {
        throw new AggregateError([failure, releaseError], `${label} operation and release both failed`);
      }
      throw releaseError;
    }
  }
}

async function releaseAfterFailure(resource: OwnedResource, error: unknown, label: string): Promise<never> {
  try {
    await resource.release();
  } catch (releaseError) {
    throw new AggregateError([error, releaseError], `${label} verification and release both failed`);
  }
  throw error;
}

export async function sendMeta(
  ctx: Context,
  request: IncomingMessage,
  response: ServerResponse,
  id: string | null,
): Promise<void> {
  const lifecycle = graphRequestLifecycle(ctx, request, response, "The client closed the graph metadata request");
  try {
    const handle = id ? await ctx.graphCapabilities.acquire(id, { signal: lifecycle.signal }) : null;
    if (!handle) {
      sendJson(response, 404, { error: "unknown graph id" });
      return;
    }
    await withOwnedResource(handle, "graph metadata capability", async () => {
      lifecycle.signal.throwIfAborted();
      const summary = handle.descriptor.graphSummary;
      const graphId = id as string;
      const capability = syntheticCapabilityFromHandle(ctx, handle);
      sendJson(response, 200, {
        schemaVersion: summary.schemaVersion,
        generatedAt: summary.generatedAt,
        nodeCount: summary.nodeCount,
        hasOverlay: false,
        environments: [],
        telemetrySources: telemetrySourceDescriptors({ kind: "none" }),
        ...syntheticExecutionBootCapability(
          graphId,
          capability?.source ?? handle.descriptor.source.metadata,
          capability?.scenarios ?? null,
          capability?.trust ?? null,
        ),
      });
    });
  } finally {
    lifecycle.dispose();
  }
}

export interface PreparedReviewViewQuery {
  readonly preparedId: string | null;
  readonly prNumber: string | null;
  readonly revision: string | null;
  readonly view: string | null;
}

export async function sendView(
  ctx: Context,
  request: IncomingMessage,
  response: ServerResponse,
  id: string | null,
  preparedQuery?: PreparedReviewViewQuery,
): Promise<void> {
  const lifecycle = graphRequestLifecycle(ctx, request, response, "The client closed the graph view request");
  try {
    if (id === null) {
      sendHtml(response, "<!doctype html><meta charset=utf-8><title>Meridian</title><p>Unknown graph id.</p>", 404);
      return;
    }
    const graphHandle = await ctx.graphCapabilities.acquire(id, { signal: lifecycle.signal });
    if (!graphHandle) {
      sendHtml(response, "<!doctype html><meta charset=utf-8><title>Meridian</title><p>Unknown graph id.</p>", 404);
      return;
    }
    await withOwnedResource(graphHandle, "graph view capability", async () => {
      if (!readGraphProjectionManifest(graphHandle.projectionDirectory)) {
        sendHtml(response, "<!doctype html><meta charset=utf-8><title>Meridian</title><p>Unknown graph id.</p>", 404);
        return;
      }
      let preparedReviewUrl: string | null = null;
      const preparedId = preparedQuery?.preparedId ?? null;
      if (preparedId !== null) {
        lifecycle.signal.throwIfAborted();
        const handoff = await ctx.preparedReviewHandoffs.resolve(preparedId, {
          signal: lifecycle.signal,
        });
        lifecycle.signal.throwIfAborted();
        if (!handoff
          || preparedQuery?.revision !== "1"
          || preparedQuery.view !== "modules"
          || preparedQuery.prNumber !== String(handoff.document.request.prNumber)
          || handoff.document.head.graphId !== id) {
          sendHtml(response, "<!doctype html><meta charset=utf-8><title>Meridian</title><p>Unknown prepared review.</p>", 404);
          return;
        }
        preparedReviewUrl = `/api/pr/prepared?id=${encodeURIComponent(preparedId)}`;
      }
      lifecycle.signal.throwIfAborted();
      const source = graphHandle.descriptor.source.metadata;
      const capability = syntheticCapabilityFromHandle(ctx, graphHandle);
      sendHtml(response, injectViewBoot(
        ctx.rendererIndex,
        id,
        source,
        capability?.scenarios ?? null,
        capability?.trust ?? null,
        preparedReviewUrl,
      ));
    });
  } finally {
    lifecycle.dispose();
  }
}

export interface ResolvedWebSyntheticCapability {
  artifactPath: string;
  sourceRoot: string;
  source: ArtifactSource;
  scenarios: import("@meridian/core").SyntheticScenarioDescriptor[];
  sourceFingerprint: string | null;
  trust: SyntheticExecutionTrust;
  signal: AbortSignal;
  release(): Promise<void>;
}

function syntheticCapabilityFromHandle(
  ctx: Context,
  handle: GraphCapabilityHandle,
): ResolvedWebSyntheticCapability | null {
  const synthetic = handle.synthetic;
  if (!synthetic
    || synthetic.capability.state !== "ready"
    || synthetic.capability.scenarios.length === 0
    || synthetic.capability.sourceFingerprint === null) return null;
  let trust: SyntheticExecutionTrust;
  if (handle.source.metadata.kind === "path") {
    if (!ctx.allowSyntheticExecution || !syntheticExecutionRuntimeSupported()) return null;
    trust = { mode: "local" };
  } else {
    const storedTrust = synthetic.executionTrust;
    if (handle.source.metadata.kind !== "github"
      || storedTrust?.mode !== "sandboxed-pr"
      || !ctx.allowSyntheticPrExecution
      || !ctx.syntheticPrSandboxRuntimeSupported()) return null;
    trust = storedTrust;
  }
  return {
    artifactPath: handle.artifactPath,
    sourceRoot: handle.source.sourceDir,
    source: handle.source.metadata,
    scenarios: synthetic.capability.scenarios,
    sourceFingerprint: synthetic.capability.sourceFingerprint,
    trust,
    signal: handle.signal,
    release: handle.release,
  };
}

/** Resolve bounded, digest-checked capability metadata without opening artifact.json. */
export async function resolveSyntheticCapability(
  ctx: Context,
  id: string | null,
  signal: AbortSignal,
): Promise<ResolvedWebSyntheticCapability | null> {
  if (id === null) return null;
  const handle = await ctx.graphCapabilities.acquire(id, { signal });
  if (!handle) return null;
  let capability: ResolvedWebSyntheticCapability | null;
  try {
    signal.throwIfAborted();
    capability = syntheticCapabilityFromHandle(ctx, handle);
  } catch (error) {
    return releaseAfterFailure(handle, error, "synthetic graph capability");
  }
  if (!capability) {
    await handle.release();
    return null;
  }
  return { ...capability, release: handle.release };
}

/** Advertise projection capability only when the immutable bundle is complete and readable. */
export async function sendProjectionManifest(
  ctx: Context,
  request: IncomingMessage,
  response: ServerResponse,
  id: string | null,
): Promise<void> {
  const lifecycle = graphRequestLifecycle(ctx, request, response, "The client closed the graph manifest request");
  try {
    const acquired = await acquireProjectionBundle(ctx, id, lifecycle.signal);
    if (!acquired || id === null) {
      sendJson(response, 404, { error: "graph projections are unavailable" });
      return;
    }
    await withOwnedResource(acquired, "graph projection manifest capability", async () => {
      lifecycle.signal.throwIfAborted();
      const bundle = projectionRegistry(ctx).get(id, acquired.root);
      const manifest = bundle.manifest;
      sendJson(response, 200, {
        version: manifest.formatVersion,
        graphId: id,
        contentId: bundle.contentIdFor(projectionQueryOptions(acquired)),
        graphSummary: manifest.graphSummary,
        repositorySummary: manifest.repositorySummary,
        defaultView: acquired.review === null
          ? defaultGraphProjectionRequest()
          : { ...defaultGraphProjectionRequest(), view: "review" as const },
      });
    });
  } finally {
    lifecycle.dispose();
  }
}

/** Serve the one disk-owned, graph-bound classification catalog shared by every PR coordinate. */
export async function sendReviewMetadata(
  ctx: Context,
  request: IncomingMessage,
  response: ServerResponse,
  searchParams: URLSearchParams,
): Promise<void> {
  const lifecycle = graphRequestLifecycle(ctx, request, response, "The client closed the review metadata request");
  try {
    const id = requiredGraphId(searchParams, "graph review metadata");
    const acquired = await acquireProjectionBundle(ctx, id, lifecycle.signal);
    if (!acquired || acquired.review === null) {
      sendJson(response, 404, { error: "review metadata is unavailable" });
      return;
    }
    await withOwnedResource(acquired, "graph review metadata capability", async () => {
      lifecycle.signal.throwIfAborted();
      const review = acquired.review!;
      // GraphCapabilityStore has already verified the peer's reciprocal descriptor and the shared
      // context/content identity. Do not reacquire and re-verify the peer generation on this hot
      // metadata path; the browser independently holds both graph capabilities for its projections.
      const headGraphId = review.side === "head" ? acquired.id : review.peerGraphId;
      const mergeBaseGraphId = review.side === "mergeBase" ? acquired.id : review.peerGraphId;
      sendJson(response, 200, reviewMetadataForContext(
        review.context,
        review.contextId,
        headGraphId,
        mergeBaseGraphId,
      ));
    });
  } finally {
    lifecycle.dispose();
  }
}

/** Materialize one bounded current-view projection from immutable disk shards. */
export async function handleGraphProjection(
  ctx: Context,
  request: IncomingMessage,
  response: ServerResponse,
  searchParams: URLSearchParams,
): Promise<void> {
  const lifecycle = graphRequestLifecycle(ctx, request, response, "The client closed the graph projection request");
  try {
    const id = requiredGraphId(searchParams, "graph projection");
    const acquired = await acquireProjectionBundle(ctx, id, lifecycle.signal);
    if (!acquired) throw new WebError(404, "graph projections are unavailable");
    await withOwnedResource(acquired, "graph projection capability", async () => {
      await handleGraphProjectionRequest({
        admission: ctx.graphProjectionAdmission,
        bundle: projectionRegistry(ctx).get(id, acquired.root),
        request,
        response,
        lifecycleSignal: AbortSignal.any([lifecycle.signal, acquired.signal]),
        queryOptions: projectionQueryOptions(acquired),
      });
    });
  } finally {
    lifecycle.dispose();
  }
}

/** Query the immutable lightweight symbol catalog for one exact graph identity. */
export async function handleGraphSymbolSearch(
  ctx: Context,
  request: IncomingMessage,
  response: ServerResponse,
  searchParams: URLSearchParams,
): Promise<void> {
  const lifecycle = graphRequestLifecycle(ctx, request, response, "The client closed the graph search request");
  try {
    const id = requiredGraphId(searchParams, "graph symbol search");
    const acquired = await acquireProjectionBundle(ctx, id, lifecycle.signal);
    if (!acquired) throw new WebError(404, "graph symbol search is unavailable");
    await withOwnedResource(acquired, "graph search capability", async () => {
      try {
        const operationSignal = AbortSignal.any([lifecycle.signal, acquired.signal]);
        const body = await readJsonBody({ request, signal: operationSignal });
        const queryStarted = performance.now();
        const result = await projectionRegistry(ctx).get(id, acquired.root).search(
          body as GraphSymbolSearchRequest,
          operationSignal,
          projectionQueryOptions(acquired),
        );
        operationSignal.throwIfAborted();
        const queryMs = performance.now() - queryStarted;
        const serializationStarted = performance.now();
        const serialized = JSON.stringify({ ...result, graphId: id });
        const serializationMs = performance.now() - serializationStarted;
        response.writeHead(200, {
          "content-type": "application/json; charset=utf-8",
          "cache-control": "no-store",
          "content-length": Buffer.byteLength(serialized),
          "server-timing": `symbol_search;dur=${queryMs.toFixed(2)}, symbol_serialize;dur=${serializationMs.toFixed(2)}`,
        });
        response.end(serialized);
      } catch (error) {
        if (error instanceof GraphSymbolSearchRequestError) throw new WebError(error.status, error.message);
        throw error;
      }
    });
  } finally {
    lifecycle.dispose();
  }
}

function requiredGraphId(searchParams: URLSearchParams, label: string): string {
  const keys = [...searchParams.keys()];
  const ids = searchParams.getAll("id");
  if (keys.length !== 1 || keys[0] !== "id" || ids.length !== 1) {
    throw new WebError(400, `${label} requires exactly one id query parameter`);
  }
  const id = ids[0] ?? "";
  if (!/^[A-Za-z0-9][A-Za-z0-9._-]{0,127}$/.test(id)) {
    throw new WebError(400, `${label} id is invalid`);
  }
  return id;
}

interface AcquiredProjectionBundle {
  readonly id: string;
  readonly root: string;
  readonly review: GraphCapabilityHandle["review"];
  readonly signal: AbortSignal;
  release(): Promise<void>;
}

async function acquireProjectionBundle(
  ctx: Context,
  id: string | null,
  signal: AbortSignal,
): Promise<AcquiredProjectionBundle | null> {
  if (id === null) return null;
  const handle = await ctx.graphCapabilities.acquire(id, { signal });
  return handle ? {
    id,
    root: handle.projectionDirectory,
    review: handle.review,
    signal: handle.signal,
    release: handle.release,
  } : null;
}

function projectionQueryOptions(
  acquired: AcquiredProjectionBundle,
): GraphProjectionQueryOptions {
  if (acquired.review === null) return {};
  const review = acquired.review;
  const headGraphId = review.side === "head" ? acquired.id : review.peerGraphId;
  const mergeBaseGraphId = review.side === "mergeBase" ? acquired.id : review.peerGraphId;
  return {
    review: {
      ...review,
      metadataId: reviewMetadataForContext(
        review.context,
        review.contextId,
        headGraphId,
        mergeBaseGraphId,
      ).metadataId,
    },
  };
}

const PROJECTION_READER_COUNT = 4;
const PROJECTION_CACHE_BYTES = 32 * 1024 * 1024;
const PROJECTION_CACHE_ENTRIES = 128;

function projectionRegistry(ctx: Context): GraphProjectionRegistry {
  return ctx.graphProjectionRegistry;
}

export interface GraphProjectionRegistryOptions {
  maxReaders?: number;
  maxCacheBytes?: number;
  maxCacheEntries?: number;
}

/**
 * Keeps a small LRU of bundle readers while one server-owned LRU owns their parsed-page memory.
 * Evicting a reader facade never exempts an in-flight query from the aggregate memory ceiling.
 */
export class GraphProjectionRegistry {
  private readonly readers = new Map<string, { root: string; bundle: GraphProjectionBundle }>();
  private readonly maxReaders: number;
  private readonly pageCache: BoundedGraphProjectionPageCache;

  constructor(options: GraphProjectionRegistryOptions = {}) {
    this.maxReaders = positiveRegistryLimit(options.maxReaders, PROJECTION_READER_COUNT, "maxReaders");
    this.pageCache = new BoundedGraphProjectionPageCache({
      maxBytes: nonNegativeRegistryLimit(options.maxCacheBytes, PROJECTION_CACHE_BYTES, "maxCacheBytes"),
      maxEntries: nonNegativeRegistryLimit(
        options.maxCacheEntries,
        PROJECTION_CACHE_ENTRIES,
        "maxCacheEntries",
      ),
    });
  }

  get(id: string, root: string): GraphProjectionBundle {
    const current = this.readers.get(id);
    if (current?.root === root) {
      this.readers.delete(id);
      this.readers.set(id, current);
      return current.bundle;
    }
    if (current) {
      this.readers.delete(id);
    }
    const bundle = new GraphProjectionBundle(root, { pageCache: this.pageCache });
    this.readers.set(id, { root, bundle });
    while (this.readers.size > this.maxReaders) {
      const oldest = this.readers.entries().next().value as [string, unknown] | undefined;
      if (!oldest) break;
      this.readers.delete(oldest[0]);
    }
    return bundle;
  }

  cacheStats(): GraphProjectionCacheStats {
    return this.pageCache.stats();
  }

  /** Release every reader facade and parsed page owned by this server instance. */
  dispose(): void {
    this.readers.clear();
    this.pageCache.clear();
  }
}

function positiveRegistryLimit(value: number | undefined, fallback: number, label: string): number {
  const effective = nonNegativeRegistryLimit(value, fallback, label);
  if (effective === 0) throw new RangeError(`${label} must be positive`);
  return effective;
}

function nonNegativeRegistryLimit(value: number | undefined, fallback: number, label: string): number {
  const effective = value ?? fallback;
  if (!Number.isSafeInteger(effective) || effective < 0) {
    throw new RangeError(`${label} must be a non-negative safe integer`);
  }
  return effective;
}
