/**
 * Commander wiring: the global options every registered subcommand shares.
 *
 * Each action forwards `optsWithGlobals()` so a command runner sees its own flags merged with
 * `--cwd/--json/--quiet` as one options object — the runners never reach back into commander.
 */

import { Command, InvalidArgumentError } from "commander";
import { readCliVersion } from "./version";
import { runGenerate } from "./commands/generate";
import type { GenerateOptions } from "./commands/generate";
import { runMock } from "./commands/mock";
import type { MockOptions } from "./commands/mock";
import { parseFailUnder, runCoverage } from "./commands/coverage";
import type { CoverageOptions } from "./commands/coverage";
import { runLink } from "./commands/link";
import type { LinkOptions } from "./commands/link";
import { runWeb } from "./commands/web";
import type { WebOptions } from "./commands/web";

export function buildProgram(): Command {
  const program = new Command();
  // Set before registering subcommands so they inherit it (via copyInheritedSettings) and
  // route their usage failures to bin's handler instead of exiting the process themselves.
  program.exitOverride();
  program
    .name("meridian")
    .description("Visualize a codebase as drill-down Unreal-Engine-Blueprints boxes.")
    .version(readCliVersion())
    .option("--cwd <dir>", "resolve relative paths against this directory")
    .option("--json", "emit a machine-readable summary on stdout")
    .option("--quiet", "suppress human progress output");
  registerGenerate(program);
  registerMock(program);
  registerWeb(program);
  registerCoverage(program);
  registerLink(program);
  return program;
}

function registerGenerate(program: Command): void {
  program
    .command("generate [path]")
    .description("Export the same canonical graph generated by the web app")
    .option("-o, --out <file>", "artifact output path", "meridian.graph.json")
    .option("--changed-since <ref>", "tag nodes changed since the merge-base with <ref> (a PR's diff) 'changed'")
    .option("--test-coverage <coverage-final.json>", "attach aggregate Istanbul coverage-map JSON (Meridian does not run tests)")
    .action((path, _options, command) => runGenerate(path ?? ".", command.optsWithGlobals() as GenerateOptions));
}

function registerMock(program: Command): void {
  program
    .command("mock-telemetry [graph]")
    .alias("mock")
    .description("Mint a deterministic mock telemetry overlay for one environment")
    .requiredOption("--env <env>", "environment to synthesize (required; never defaults)")
    .option("-o, --out <file>", "overlay output path (default meridian.overlay.<env>.json)")
    .option("--seed <seed>", "deterministic seed", "")
    .action((graph, _options, command) =>
      runMock(graph ?? "meridian.graph.json", command.optsWithGlobals() as MockOptions),
    );
}

function registerWeb(program: Command): void {
  program
    .command("web [source]")
    .description("Open the app for a repository source or an existing graph artifact")
    .option("--port <number>", "preferred port (walks forward if busy)", parsePort, 4180)
    .option("--host <host>", "host to bind", "127.0.0.1")
    .option("--no-open", "do not open a browser")
    .option("--refresh-cache", "re-extract remote graphs while reusing cached checkouts")
    .option("--github-client-id <id>", "GitHub OAuth app client id for sign-in (default: the project's app; also read from MERIDIAN_GITHUB_CLIENT_ID)")
    .option("--overlay <source>", "existing-graph overlay source: a file path or 'mock'")
    .option("--env <env>", "existing-graph environment (also read from BLUEPRINT_ENV)")
    .option("--source-root <dir>", "existing-graph source root for code view")
    .option("--test-coverage <coverage-final.json>", "attach aggregate Istanbul coverage to an existing graph")
    .action((source, _options, command) => runWeb(source, command.optsWithGlobals() as WebOptions));
}

function registerCoverage(program: Command): void {
  program
    .command("coverage [graph]")
    .description("Report static test coverage derived from the graph's call reachability")
    .option("--fail-under <percent>", "exit non-zero when coverage is below this percentage", parseFailUnder)
    .action((graph, _options, command) =>
      runCoverage(graph ?? "meridian.graph.json", command.optsWithGlobals() as CoverageOptions),
    );
}

function registerLink(program: Command): void {
  program
    .command("link <graphs...>")
    .description("Join two or more graph artifacts into one system graph via their IPC channel keys")
    .option("-o, --out <file>", "linked artifact output path", "meridian.system.json")
    .option("--name <name>", "display name for the linked system (default: the joined source names)")
    .action((graphs, _options, command) => runLink(graphs, command.optsWithGlobals() as LinkOptions));
}

function parsePort(value: string): number {
  const port = Number(value);
  if (!Number.isInteger(port) || port < 1 || port > 65535) {
    throw new InvalidArgumentError("port must be an integer in 1..65535");
  }
  return port;
}
